-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Dec 13, 2024 at 10:19 AM
-- Server version: 8.0.30
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `voyageur_bags`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id` int NOT NULL,
  `username` varchar(25) NOT NULL,
  `password` varchar(30) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `username`, `password`, `created_at`, `deleted_at`) VALUES
(1, 'admin1', '123', '2024-06-01 04:52:17', '2024-06-01 04:52:17');

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `category_id` int NOT NULL,
  `category_name` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`category_id`, `category_name`, `image`, `description`, `created_at`, `deleted_at`) VALUES
(28, 'Classic Backpacks', 'classic_Bagpacks.png', 'This category will contain all Classic Backpacks', '2024-06-08 02:30:59', NULL),
(29, 'Suitcases', 'Suitcases.jpg', 'This category will contain all Suitcases', '2024-06-08 02:30:59', NULL),
(30, 'Tote Bags', 'Tote_Bags.jpg', 'This category will contain all Tote Bags', '2024-06-08 02:30:59', NULL),
(31, 'Duffle Bags', 'Duffle_bag.jpg', 'This category will contain all Duffle Bags', '2024-06-08 02:30:59', NULL),
(34, 'Garment Bags', 'Garment_Bags.jpg', 'This category will contain all Garment Bags', '2024-06-08 02:30:59', NULL),
(35, 'For Professionals', 'For_Professionals.jpg', 'This category will contain all For Professionals', '2024-06-08 02:30:59', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `items`
--

CREATE TABLE `items` (
  `id` int NOT NULL,
  `on_sale` tinyint(1) NOT NULL DEFAULT '0',
  `home_items` int NOT NULL DEFAULT '0',
  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `category` varchar(30) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `about_this_product` text NOT NULL,
  `caption` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `item_weight` float DEFAULT NULL,
  `generic_name` varchar(255) DEFAULT NULL,
  `percentage` int DEFAULT NULL,
  `price` int DEFAULT NULL,
  `discounted_price` int DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `items`
--

INSERT INTO `items` (`id`, `on_sale`, `home_items`, `name`, `category`, `description`, `about_this_product`, `caption`, `item_weight`, `generic_name`, `percentage`, `price`, `discounted_price`, `image`, `created_at`, `deleted_at`) VALUES
(45, 0, 0, 'TRAVALATE Duffle Bag', '28', 'TRAVALATE 50L Foldable Travel Duffle Bag with Separate Shoe Compartment and Adjustable Shoulder Strap | Water and Tear Resistant Overnight Bag for Men & Women – Black', 'Premium High-Strength Fabric: Crafted from premium, lightweight polyester fabric, this black backpack offers exceptional durability and water resistance, while the vibrant teal highlights make it extremely easy on the eyes. The easy-to-clean material ensures your backpack remains pristine, no matter where your journey takes you.\r\n\r\nEasy Access: This backpack features a unique fold-top opening for maximum storage and a secure strap closure for adjustable volume. A collapsible partition offers direct access to the main compartment from the laptop area offering easy retrieval of items.\r\n\r\nUncompromising Comfort and Convenience: Experience unparalleled comfort with superior back and sleeve padding, designed for extended wear. The intuitive trolley sleeve enhances mobility, ensuring your journey is as seamless as it is enjoyable.\r\n\r\n12 Month International Warranty: Maintenance is straightforward-simply wipe to clean. Coupled with a 12-month international warranty.\r\n\r\nDesigned with an internal organiser, easy access pockets and a hidden pocket for valuables, this backpack keeps items clutter-free and ensures that everything has its place.', '                            \r\n                                                        \r\n                                                        \r\n                                                        \r\n                            ', 1.2, 'Formal Backpack', 10, 1799, 1619, 'product1.png', '2024-12-04 04:30:39', NULL),
(46, 0, 1, 'Thorium Neo Suitcase', '29', 'Thorium Neo 8 Wheels 66 Cm Medium Check-in Trolley Bag Hard Case Polycarbonate 360 Degree Wheeling System Luggage, Trolley Bags for Travel, Speed_Wheel Suitcase for Travel, Graphite Blue', 'Textured Scratch resistant Polycarbonate shell\r\n\r\nThis lightweight trolley luggage comes with a Fixed combination Lock, 8 wheels with smooth maneuverability, and contrast beading that gives a premium look to the product\r\n\r\nThorium Neo is for every traveler who is looking for smart looking luggage with good utility point, Because of its new age trendy colors and contrast beading, the bag suits every need be it business or leisure travel. \r\n\r\nThe design on the bag gives it a very unique appearance.\r\n\r\nThe polycarbonate shell protects your luggage from scratches and mishandling.\r\n\r\nThe 5 year international Warranty ensures we have got you covered on all your trips.', '                                                        \r\n                                                        \r\n                                                        \r\n                                                        \r\n                       ', 3, 'Luggage', 0, 3999, 3999, 'product2.png', '2024-06-19 00:53:29', NULL),
(48, 0, 0, 'Van Gogh Printed Tote Bag', '30', 'Peach Blossom Van Gogh Printed Tote Bag for Women with Zip, Stylish Cotton Handbags, Canvas Tote Bags for College', 'Quality : Our Cotton Reusable Tote Bags are not only environmentally safe, but they are also built to last. With their exceptional strength-to-weight ratio and cross-stitched handles, these bags can comfortably carry a full load of groceries or a day\'s worth of supplies.\r\n\r\n\r\n\r\nOccasion : Our cotton bags are perfect for a variety of occasions. Whether you\'re going to the grocery shopping or need storage, these versatile bags are up for the task. With their spacious size and durability, they can hold more than single-use plastic bags and can be used repeatedly in your everyday life. By choosing these reusable cotton bags, you\'re making a sustainable choice that helps reduce plastic waste.\r\n\r\n\r\n\r\nPrint : We use Heat and Vinyl transfers for the prints.Recommending a gentle machine wash that can survive the wash cycle also do not iron on print.\r\n\r\n\r\n\r\nWash care : To keep our cotton bags in good condition,it\'s best not to wash them too often because the cotton fabric might shrink a little (about 5-10%). If you do need to wash them, use cold water and mild detergent. Make sure they\'re fully dry before ironing or adding vinyl transfers. Be careful with extreme conditions as they can affect the fabric\'s shape. By following these simple steps, you can keep our cotton shopping bags looking great and lasting a long time.', '                                                        \r\n                                                        \r\n                                                        \r\n                                                        \r\n                       ', 0.24, 'tote bag', 0, 1499, 1499, 'product3.png', '2024-06-19 00:53:43', NULL),
(49, 0, 1, 'Lyrovo Canvas Tote Bag', '30', 'Lyrovo Canvas Tote Bag for Women Purse Handbag', 'STURDY & DURABLE:6.5\" handle length, this printed canvas large tote bag for women is perfect as large capacity bag for women & ideal for daily use. The design shown appears on both sides.\r\n\r\n\r\n\r\nREASONS TO BUY LYROVO SHOPPING BAGS – These Shoppers tote can be reusable as Tote Bag | Shoppers bag | Handbag | Grocery Bag | Travel Bag |\r\n\r\nStorage Bag | Gift Bag for Diwali Gifting | Hand Bag | Party Bag | Multipurpose Jute bag is perfect bag for everyday shopping\r\n\r\n\r\n\r\nCARE INSTRUCTIONS: Dry Clean , It is recommended that a wet cloth is used to clean the bag', 'Crafted for versatility, designed for every journey.                            \r\n                                                        \r\n                                                        \r\n                            ', 0.4, 'Tote Bags', 0, 2499, 2499, 'product4.png', '2024-06-19 00:53:55', NULL),
(50, 0, 0, 'Uppercase Medium Backpack', '28', 'Backpack 3x more water resistant sustainable bag with Rainproof zippers for Men, Women, Boys and Girls', 'GRS CERTIFIED BACKPACK- Embrace sustainability without compromising on quality with our GRS-certified uppercase Daypack School/ College Bag. Made with over 50% recycled materials (License No. CMPY-158596), it features a padded compartment with breathable back padding with Air mesh, ensuring comfort and eco-conscious style for your journeys.\r\n\r\n\r\n\r\nWRINKLE-FREE & WATER RESISTANT BACKPACK- Experience unparalleled durability and style with our uppercase Daypack School/Office Bag. Handcrafted with premium, robust materials for a wrinkle-free, water-resistant design, featuring rainproof zippers for ultimate protection. Elevate your journey with this top-quality, long-lasting backpack!\r\n\r\n\r\n\r\nTROLLEY SLEEVE- Enhance your travel convenience with the uppercase. This backpack is equipped with a trolley sleeve, ensuring secure placement on your luggage. Effortlessly merge style and functionality while travelling.\r\n\r\n\r\n\r\nSTURDY STITCHING & VERSATILE STORAGE FOR YOUR ESSENTIALS- The uppercase Daypack school/college bag is meticulously designed with sturdy stitching, ensuring the right size for all essentials. Crafted for durability and functionality, it\'s an ideal companion for academic or professional pursuits, promising reliability and style in every stride.', '                            \r\n                                                        \r\n                            ', 0.38, 'Formal Backpack', 0, 4499, 4499, 'product5.png', '2024-06-19 00:54:10', NULL),
(51, 0, 0, 'Handcuffs Carry Garment Bag', '34', 'Handcuffs Carry On Bag Garment Bags for Travel Women Men Convertible Duffle Bag with Shoe Compartment Shoulder Strap, 2 in 1 Hanging Dress Suit Bag Weekend Bag (Black)', 'Feature: durable, lightweight, and water-resistant luggage suitcase strap along the back is convenient for fixing the foldable garment bag on the trolley of luggage, to secure the foldable garment bag slip over the handle of any rolling luggage for hands-free transport and make travelling simpler wrapped handles, convenient and comfortable for carrying.\r\n\r\nDetachable adjustable shoulder strap can adjust it to fit your shoulder well, provide a different way to carry-on, you can take it off whenever you need. As a good valentines day gifts for him her, thanksgiving gifts for men women metal hooks of strap is super sturdy;\r\n\r\nEasy to use strap attaches to joining d rings for max support. Luggage sleeve can be anti-theft and have lost-theft function high quality smooth zipper is made with sturdy titanium alloy material, ensure a secure & offering long time usage to carry on padded foam buckle tie holds your garments in place, ensuring that they don’t crease or crumple during travel well made of high density and water repellent polyester fabric, not easy get wet and ensure long lasting usage metal chain and hook support hang up in a closet or from a door at Handcuffs.\r\n\r\nHandcuffs provide the highest quality bags with the most reasonable cost so every customer can find a bag they actually love to carry. After assembly of large size beg for male female formal casual tour. To create products that inspire people to get out and live passionate lives; exploring, creating, and living life in the moment.', 'Elevate your style, but never compromise on security                            \r\n                                                        \r\n                                                        \r\n                            ', 1, 'garment Bags', 0, 6799, 6799, 'product6.png', '2024-06-19 00:54:23', NULL),
(52, 0, 1, 'Urban Jungle Venture Workpack', '28', 'Premuim Urban Jungle Venture Workpack 23 Liters Water Resistant, L-Open, Premium Polyester Laptop Backpack', 'Premium High-Strength Fabric: Crafted from premium, lightweight polyester fabric, this black backpack offers exceptional durability and water resistance, while the vibrant teal highlights make it extremely easy on the eyes. The easy-to-clean material ensures your backpack remains pristine, no matter where your journey takes you.\r\n\r\n\r\n\r\nEasy Access: This backpack features a unique fold-top opening for maximum storage and a secure strap closure for adjustable volume. A collapsible partition offers direct access to the main compartment from the laptop area offering easy retrieval of items.\r\n\r\n\r\n\r\nSuperior Laptop Protection and Organization: The 180-degree flat-open laptop and tablet sleeve, fits up to a 16\" laptop, allows for easy laptop and tablet access and robust protection. Designed with an internal organiser, easy access pockets and a hidden pocket for valuables, this backpack keeps items clutter-free and ensures that everything has its place.\r\n\r\n\r\n\r\nUncompromising Comfort and Convenience: Experience unparalleled comfort with superior back and sleeve padding, designed for extended wear. The intuitive trolley sleeve enhances mobility, ensuring your journey is as seamless as it is enjoyable.\r\n\r\n12 Month International Warranty: Maintenance is straightforward-simply wipe to clean. Coupled with a 12-month international warranty, this backpack stands as a testament to Urban Jungle\'s commitment to quality, offering peace of mind with every adventure. ', 'Adventure-ready!!                       \r\n                            ', 0.8, 'Formal Backpack', 10, 6999, 6299, 'product7.png', '2024-06-22 02:32:13', NULL),
(53, 0, 0, 'Premuim A/T Suitcase', '29', 'Premuim Trolley Bag for Travel FRONTEC Polycarbonate Hardsided Small Cabin Luggage Bag Suitcase for Travel', 'Durable Construction: Made from high-quality, lightweight polycarbonate material that resists impact and protects your belongings.\r\n\r\nExpandable Design: The suitcase features an expandable zipper, allowing for additional packing space when needed.\r\n\r\nSmooth Mobility: Equipped with four 360-degree spinner wheels, ensuring effortless maneuverability in all directions.\r\n\r\nSecure Locking System: Includes an integrated TSA-approved lock for added security and peace of mind during travel.\r\n\r\nErgonomic Handles: Telescopic handle with multiple height settings and comfortable top and side carry handles for easy lifting.\r\n\r\nSpacious Interior: Fully lined interior with multiple compartments, including a zippered divider, mesh pockets, and compression straps to keep your items organized and in place.\r\n\r\nStylish Design: Available in various colors and finishes, the Premium A/T Suitcase boasts a sleek and modern look suitable for any traveler.', '                            \r\n                                                        \r\n                                                        \r\n                            ', 1.35, 'Suitcases', 0, 14999, 14999, 'product8.png', '2024-06-19 00:54:40', NULL),
(56, 0, 0, 'Vanguard Camera Backpack', '35', 'Vanguard Camera Backpack Contains VEO Select 47 BF I 1-2 Pro DSLRs with lens upto 70-200mm,3-4 lenses, flash and accessories, Upto 15 inch(39cm), laptop, Tablet, WaterProof', 'Durable Build: Constructed from high-quality, weather-resistant materials to protect your gear from the elements.\r\n\r\nCustomizable Interior: Fully padded, adjustable dividers allow for personalized organization, accommodating various camera bodies, lenses, drones, and accessories.\r\n\r\nQuick Access: Side access panel provides instant reach to your camera, so you never miss a shot.\r\n\r\nComfortable Carry: Ergonomically designed shoulder straps, back padding, and adjustable waist belt distribute weight evenly for all-day comfort.\r\n\r\nDedicated Compartments: Separate compartments for a laptop up to 15 inches, a tablet, and personal items, keeping your tech and essentials organized and within reach.\r\n\r\nTripod Holder: External straps secure a tripod or monopod, ensuring you have all your gear with you.\r\n\r\nProtective Rain Cover: Included rain cover offers extra protection in inclement weather, ensuring your equipment stays dry and safe.\r\n\r\nTravel-Friendly: Meets carry-on size requirements for most airlines, making it a perfect companion for photographers on the go.', '                            \r\n                                                        \r\n                                                        \r\n                                                        \r\n                            ', 0.7, 'Formal Backpack', 0, 11999, 11999, 'product9.png', '2024-06-26 02:40:41', NULL),
(57, 0, 1, 'Cpixen Travel Backpack', '28', 'Cpixen Travel Backpack Large Capacity Men\'s Mother Bag Female Oxford Cloth College Student Bag ShouldeBag High Capacity Travel Bag', 'Durable Construction: Made from high-density, water-resistant polyester fabric, ensuring durability and protection from the elements.\r\n\r\nLarge Capacity: Spacious main compartment with multiple pockets and internal organizers for packing clothes, shoes, and travel essentials.\r\n\r\nSeparate Laptop Compartment: Padded compartment fits up to a 17-inch laptop and a tablet, keeping your devices secure and easily accessible.\r\n\r\nExternal USB Port: Built-in USB charger outside and built-in charging cable inside, offering convenient charging of your electronic devices on the go (power bank not included).\r\n\r\nComfortable Design: Ergonomic shoulder straps with adjustable chest strap and ventilated back padding for comfort and support during long journeys.\r\n\r\nAnti-Theft Features: Hidden zipper closures and a back pocket design for added security against pickpockets.\r\n\r\nWater Bottle Pockets: Dual side pockets for carrying water bottles or umbrellas, keeping hydration and rain gear easily accessible.\r\n\r\nVersatile Use: Suitable for various travel activities, including hiking, camping, business trips, and daily commuting.', 'Two Bags, One Purchase\r\nCustomize Your Carry                            \r\n                                                        \r\n                                                        \r\n                            ', 1.2, 'Formal Backpack', 0, 14999, 14999, 'bag3.png', '2024-12-01 06:04:47', NULL),
(58, 1, 0, 'New SBS Laptop Bag', '28', 'New SBS Waterproof Men Laptop Bags Computer Backpack with USB for Travel College School', 'Premium Materials: Crafted from high-quality, water-resistant nylon material, ensuring durability and protection against light rain and spills.\r\n\r\nPadded Laptop Compartment: Dedicated compartment with thick padding to safeguard laptops up to 15.6 inches, providing peace of mind while on the move.\r\n\r\nMultiple Compartments: Spacious main compartment with organizational pockets for documents, notebooks, and accessories such as chargers, pens, and keys.\r\n\r\nQuick Access Pocket: Front zippered pocket for easy access to frequently used items like smartphones, wallets, or passports.\r\n\r\nComfortable Carry: Adjustable shoulder strap with padding for comfortable wear over the shoulder or cross-body, plus sturdy handles for alternative carrying options.\r\n\r\nVersatile Design: Suitable for both men and women, with a minimalist yet stylish design that complements various outfits and settings.\r\n\r\nTravel-Friendly: Slim profile that fits under most airline seats, making it ideal for air travel or daily commuting.\r\n\r\nSecurity Features: Zippered closure and discreet pocket design to keep belongings secure while on the move.', 'Pack Your Dreams, Pursue Your Passion                            \r\n                            ', 1.3, 'Formal Backpack', 24, 6999, 5319, 'bag4.png', '2024-06-19 00:56:55', NULL),
(59, 1, 1, 'Loowoko Hiking Backpack', '35', 'Loowoko 50L Hiking Backpack, Waterproof Camping Essentials Bag with Rain Cover, 45+5 Liter Lightweight Backpacking Back Pack', 'Spacious Capacity: 50 liters of storage space with multiple compartments and pockets to organize gear efficiently.\r\n\r\nDurable Material: Made from high-quality, tear-resistant and water-repellent nylon fabric, designed to withstand the rigors of outdoor activities.\r\n\r\nComfortable Carrying System: Adjustable shoulder straps, chest strap, and padded waist belt distribute weight evenly, reducing strain on your shoulders and back.\r\n\r\nVentilation System: Breathable mesh back panel promotes airflow and keeps you cool during strenuous hikes.\r\n\r\nExternal Attachment Points: Various attachment loops and D-rings for hanging trekking poles, sleeping bags, or other gear externally.\r\n\r\nHydration System Compatible: Includes a hydration bladder compartment and tube access port (hydration bladder not included).\r\n\r\nRain Cover: Integrated rain cover stored in a bottom pocket for added protection during wet weather.\r\n\r\nVersatile Use: Suitable for hiking, camping, trekking, and other outdoor activities.\r\n', 'A Perfect Backpack for day hiking trips                            \r\n                                                        \r\n                            ', 1.8, 'Professional Backpacks', 50, 19999, 10000, 'bag2S.png', '2024-06-18 23:59:55', NULL),
(64, 0, 1, 'Miraggio Oversized Melissa Tote Bag', '28', 'Miraggio Oversized Melissa Tote Bag for Women with Adjustable & Detachable Sling Strap', 'TRENDY AND STYLISH, LATEST HANDBAGS FOR WOMEN: Set yourself a class apart and inspire the rest by carrying this Melissa Tote Bag from Miraggio. To stay ahead of the fashion pack, this tote is a must-have for your formal/office looks. Designed specially to serve the needs of working-class women. Inspired by and made for the quintessential Modern Woman!\r\nSPACIOUS HANDBAG FOR WOMEN: Melissa Oversized Tote Bag comes with 2 Main Compartment, 2 slip pockets and 1 zip pocket. This tote has space that fits your essentials easily like laptop (upto16\"), tablet, makeup pouch, phone & charger, tit-bits etc. Assured to hold your belongings safe with a zipper closure. It features 2 handles attached with metal loops to provide easy grip.\r\nYOUR TAKE EVRYWHERE TOTE: Roomy enough for all travel must-haves and more. The bag’s square shape affords plenty of room. It comes in two classic colors, ivory(with contrasting trims) & black.\r\nPREMIUM QUALITY HANDBAG FOR WOMEN: Crafted from signature - Faux leather comes with quality and durability. This classic tote comes with 2 handles and a detachable & Adjustable crossbody strap, making it a multi-purpose bag. Carry it as a top-handle bag, or even utilize the adjustable strap to use it as a shoulder bag or even crossbody.', '                            \r\n                                                        \r\n                                                        \r\n                            ', 0.5, 'Tote Bags', 8, 2999, 2759, 'product10.png', '2024-12-01 06:03:21', NULL),
(65, 0, 1, 'Storite Nylon Travel Duffle Bag', '31', 'Storite Nylon 47 Cm Imported Travel Duffle Bag, Sports Shoulder Bag for Women with Wet Pocket & Shoe Compartment Weekender Overnight Luggage Bag', 'he Travel Duffle Bag is elegant, fashionable and practical.\r\nThe Duffle Bag is perfect to help you carrying your traveling essentials, keeps your belongings organized.\r\nIt is designed with large capacity and wet pocket.\r\nMulti-zone design can provide exclusive space for luggage. The main compartment provides effective protection , and small luggage is placed in the exclusive compartment to keep the luggage neat and orderly.', '                            \r\n                            ', 0.8, 'Duffel Bags', 0, 1699, 1699, 'product11.png', '2024-06-26 03:13:19', NULL),
(73, 0, 1, 'LOOM TREE Art Portfolio Case Bag', '35', 'LOOM TREE Art Portfolio Case Portfolio Backpack Art Portfolio Carry Bag for Artwork | Art Supplies | Other Art Supplies', 'Water Resistancethe Art Portfolio Tote Bag Is Made Of Oxford Cloth Material, Rubber Handle, Adjustable Shoulder Strap, Lightweight And Waterproof To Protect Your Items Of Kind Artwork. Designthe Art Portfolio Case Includes A Top Handle And Adjustable Shoulder Straps For Comfortable Portability. Perfect For Traveling, Transporting Bag Organizer Supplies, And Other Stuff. Zipper Closurethe Portfolio Bag Comes With Convenient Zipper Closure, Art Portfolio Case Secures Your Precious Paints While Traveling. Portable Sizelength 54Cm/21.26Inch; Width 40Cm/15.75Inch; Thickness 1Cm/0.39Inch. Designed With Large Capacity, The Interior Of The Art Portfolio Case Is Built With A Full Width Interior Pocket To Carry Your Extra Supplies.', '                            \r\n                            ', 0.8, 'For Professionals', 0, 2499, 2499, 'poduct12.png', '2024-12-01 06:03:54', NULL),
(75, 0, 0, 'Herschel Supply Co. Little America Backpack', '28', 'Herschel Supply Co. Little America Backpack blends timeless mountaineering aesthetics with modern functionality', 'The Herschel Supply Co. Little America Backpack is renowned for its iconic blend of vintage mountaineering style and contemporary practicality. Its exterior is crafted with durable materials that exude rugged sophistication, making it suitable for both urban commutes and outdoor adventures. The backpack features a spacious main compartment secured by a drawstring closure and magnetic strap fastenings, offering easy access to its contents.\r\n\r\nInside, you\'ll find a plush, fleece-lined sleeve designed to safeguard laptops up to 15 inches in size, ensuring your tech essentials stay protected on the move. The backpack\'s front pocket provides additional organization for smaller items like keys, phones, and chargers, keeping them within quick reach. Comfort is prioritized with padded, ergonomic shoulder straps and a ventilated air mesh back panel that enhances airflow and reduces strain during extended wear.\r\n\r\nWhether you\'re navigating city streets or exploring remote trails, the Herschel Little America Backpack combines functional design with enduring style, making it a versatile companion for professionals, students, and adventurers alike.', '', 0.75, 'Formal Backpack', 0, 13999, 13999, 'product14.png', '2024-06-26 01:53:58', NULL),
(76, 0, 0, 'DroneGuard CS 400 from Lowepro', '35', 'DroneGuard CS 400 from Lowepro - Safely Carry and Organize All Your Quadcopter Drone Equipment in This Protective Case', 'The Drone Guard 400 case fits: DJI Phantom 1, 2 or 3, or 3DR Solo, or similar drone, quadcopter or flying camera form factor, RC/transmitter, blades, props, GoPro or other action video camera, batteries, cables, chargers, mounts, manuals, tools, etc.\r\nThe perfect, out-of-the-box solutions for carrying, organizing, storing and protecting your drone gear and all essentials\r\nForm Shell technology with lightweight, yet sturdy composite-shell construction offers superior protection for gear without adding weight or bulk\r\nA lightly padded back-pad includes attachable back-pad straps. Use for treks out to your flying location, or detach and pack away for less bulk or for long-distance travel\r\nIncludes dedicated storage for blades, props, GoPro or other action video camera, batteries, cables, chargers, mounts, manuals, etc.', '', 1.56, 'For Professional', 0, 7499, 7499, 'product13.png', '2024-06-26 02:00:09', NULL),
(77, 0, 1, 'CASALE Garment Bag', '34', 'Carry on Garment Bags Convertible Suit Bag with Shoes Compartment Waterproof 2 in 1 Travel Large Garment Bags Garment Duffle Bag for Men Black, Black', 'The carry on garment bag is made of high-quality polyester fiber, with shock-resistant and water-resistant/tear-resistant properties, which can better protect your suit or dress. The high-quality YKK zipper/buckle and hardware design can provide safety and durability for your business trip or vacation. The luggage strap on the back makes it easier for you to carry suitcases and clothing bags with you.When unfolded, it is a suit bag, and when assembled, it becomes a travel bag. This large garment bag is also designed with a shoe bag with a waterproof lining and two vents to store your shoes or clothes and separate wet and dirty shoes from the main compartment. A non-slip wear-resistant base is added to the bottom of the suit bag, which can provide safer and more stable protection when driving or going out in an airplane.The interior of the garment bags for travel has a large space and 2 inner buckles, which can keep your suit and clothes neat and wrinkle-free. And the 2 in 1 travel duffle bag has an extended inner lining, which can easily carry 2 suits and 1 dress, so that there are no more wrinkles on your dress or suit. The carry on garment bag comes with a hook design, you can hang the bag on the door or on the wall to save more space.', '', 1.2, 'Garment Bags', 0, 4999, 4999, 'product15.png', '2024-06-26 03:12:39', NULL),
(78, 0, 0, 'Assembly Cabin Suitcase', '29', 'Assembly Cabin Luggage Polycarbonate 20 Inches - Premium Hard-Sided Trolley Bag for Travel (Blue White, 40 L)-Stark', '100% Polycarbonate Material - Hard shell Cabin Luggage || Water & Scratch Resistant Suitcase\r\nKeyless TSA Lock Trolley Bag || 8 Spinner Wheels Luggage || Retractable Telescopic Trolley Handle\r\nAdditional Laptop Compartment (Upto 15.6 Inches Laptop) || Cabin Bag Capacity: 40 L || Dimension: 34cm, 24.5cm, 55cm (LxWxH)\r\nComplimentary Packing Organizer kit - 1 Toiletry Kit, 1 Packing Cube and 1 Shoe Bag\r\n5 Years of Warranty on Manufacturing Defects || To Register Your Warranty Kindly Scan the QR Code Attached to the Product.', '', 1.8, 'Suitcase', 0, 8499, 8499, 'product16.png', '2024-06-26 02:12:28', NULL),
(79, 0, 0, 'Delsey Paris Tiphanie Suitcase', '29', 'Delsey Paris Tiphanie 76 cms Large Check-in Polycarbonate Hard-sided 4 Double Wheel Luggage/Suitcase/Trolley Bag for Travel with TSA Lock (Steel Blue)', 'Delsey Paris\'s trolley bags for travel are a blend of Polycarbonate and ABS which make these travel bags for luggage extremely durableFour spinner wheels suitcase for travel with stable & multi-directional rolling\r\nIntegrated 3-dial TSA approved combination lock trolley bag/ luggage bag for travelCheckin trolley bag with spinner wheels: Enjoy the peace of mind with 2 year manufacturer warranty for our trolley bags for travel that includes the cost of repair for damage incurred from airlines or other common carriers. This applies when purchased as new and after registration', '                            \r\n                                                        \r\n                            ', 4.2, 'Suitcase', 0, 10499, 10499, 'product17.png', '2024-06-26 03:02:46', NULL),
(80, 0, 0, 'Storite Nylon Tarvel Duffle Bag', '28', 'Storite Nylon 51 cms Imported Travel Duffle Bag Muti- Pocket Sports Shoulder Bag for Women with Wet Pocket & Shoe Compartment Weekender Overnight Travel Luggage Bag (Green/White - 51x22x26 cm)', 'The Storite Nylon 51 cms Imported Travel Duffle Bag is designed for both functionality and style, making it an ideal choice for sports enthusiasts and travelers alike. Crafted from durable nylon, this duffle bag offers reliability and longevity, capable of withstanding the rigors of frequent use.\r\n\r\nIt features a spacious main compartment that provides ample room for your belongings, whether you\'re packing for a weekend getaway or carrying your gym essentials. The bag is equipped with multiple pockets, strategically placed to help you stay organized and store smaller items such as keys, wallets, and electronic gadgets conveniently.\r\n\r\nFor added convenience, the duffle bag includes sturdy handles and an adjustable shoulder strap, allowing you to carry it comfortably according to your preference. Its compact size, measuring 51 cms, ensures easy portability while complying with most airline carry-on restrictions.', '                            \r\n                            ', 0.45, 'Duffle Bag', 0, 3499, 3499, 'product18.png', '2024-06-26 02:25:35', NULL),
(81, 0, 0, 'PALAY Duffle Bags Travel Bags for Women', '31', 'PALAY® Duffle Bags Travel Bags for Women PU Waterproof Large Travel Duffel Bag Carry on Shoulder Bag with Shoulder Strap Carry On Bag for Trip', 'This travel luggage bag uses a high-quality PU leather construction, ensuring durability and longevity. The premium leather material not only enhances the bag\'s overall appearance and texture but also offers resistance against wear and tear. Whether you are traveling frequently or occasionally, this bag is built to withstand the rigors of your journeys, ensuring its longevity.Designed with trendy print patterns, this travel luggage bag adds a touch of style to your travels. Simple prints plus the elegant color design, these fashion prints allow you to express your personal style. Stand out from the crowd with this eye-catching bag, which is both practical and fashionable for any travel occasion. Also beautful and unique prints design also makes it convenient for you to find your bag during travels.Featuring one main large compartment and one small compartment, this travel luggage bag offers ample space for your essentials. It comfortably accommodates the clothing and toiletries of 1-2 people, making it ideal for short trips. The well-organized design ensures that your belongings remain tidy and easily accessible throughout your journey.', '', 0.8, '', 0, 7499, 7499, 'product19.png', '2024-06-26 02:25:19', NULL),
(82, 0, 0, 'Swiss Military Duffle Bag for Gym', '31', 'Swiss Military Duffle Bag for Gym, Duffle Bags for Travel, Men, Women| Spacious Gym Bag, Adj. Shoulder Strap & Comfortable Handle, Premium Polyester, Durable Zippers, Multi-Purpose, 27L, Grey', 'The Swiss Military Duffle Bag offers ample space for gym essentials, making it the perfect companion for your workouts. With an adjustable shoulder strap and comfortable handle, this duffle bag provides versatile and comfortable carrying options.Crafted from water-resistant fabric, this duffle bag keeps your belongings dry and protected from unexpected spills or light rain during outdoor activities.Made with sturdy materials and durable zippers, this multi-purpose duffle bag is built to withstand the rigors of travel and gym use.Ideal for gym sessions, travel, and everyday use, this duffle bag is designed to meet the needs of both men and women.', '', 0.5, 'Gym Duffel\'s', 0, 11499, 11499, 'product20.png', '2024-06-26 02:34:58', NULL),
(83, 0, 0, 'Fur Jaden Eco Conscious Vegan Garment Bag', '34', 'Fur Jaden Eco Conscious Vegan Leather Sustainable Garment Bag 40L Travel Weekender Cabin Bag with External Shoe Compartment (Tan)\r\nColour:Brown', 'Made from cruelty-free and eco-friendly materials, this duffle bag is a testament to our commitment to sustainable fashion. Built to endure the rigors of travel, the duffle bag features robust stitching and quality materials for long-lasting durability.Comfortably carry your duffle bag with ease using the padded grab handles, providing a soft grip for stress-free transportation. Adjustable Shoulder Strap: Customize your carrying experience with the adjustable and detachable shoulder strap, offering flexibility and comfort during extended journeys.Pack everything you need for your journey with the ample 40-liter capacity, providing room for clothing, essentials, and more. Ideal for weekend getaways, gym sessions, or short trips, this duffle bag combines functionality with a sleek and versatile design.', '', 1.2, 'Garment Bag', 0, 8999, 8999, 'product21.png', '2024-06-26 03:27:24', NULL),
(45, 0, 0, 'TRAVALATE Duffle Bag', '28', 'TRAVALATE 50L Foldable Travel Duffle Bag with Separate Shoe Compartment and Adjustable Shoulder Strap | Water and Tear Resistant Overnight Bag for Men & Women – Black', 'Premium High-Strength Fabric: Crafted from premium, lightweight polyester fabric, this black backpack offers exceptional durability and water resistance, while the vibrant teal highlights make it extremely easy on the eyes. The easy-to-clean material ensures your backpack remains pristine, no matter where your journey takes you.\r\n\r\nEasy Access: This backpack features a unique fold-top opening for maximum storage and a secure strap closure for adjustable volume. A collapsible partition offers direct access to the main compartment from the laptop area offering easy retrieval of items.\r\n\r\nUncompromising Comfort and Convenience: Experience unparalleled comfort with superior back and sleeve padding, designed for extended wear. The intuitive trolley sleeve enhances mobility, ensuring your journey is as seamless as it is enjoyable.\r\n\r\n12 Month International Warranty: Maintenance is straightforward-simply wipe to clean. Coupled with a 12-month international warranty.\r\n\r\nDesigned with an internal organiser, easy access pockets and a hidden pocket for valuables, this backpack keeps items clutter-free and ensures that everything has its place.', '                            \r\n                                                        \r\n                                                        \r\n                                                        \r\n                            ', 1.2, 'Formal Backpack', 10, 1799, 1619, 'product1.png', '2024-12-04 04:30:39', NULL),
(46, 0, 1, 'Thorium Neo Suitcase', '29', 'Thorium Neo 8 Wheels 66 Cm Medium Check-in Trolley Bag Hard Case Polycarbonate 360 Degree Wheeling System Luggage, Trolley Bags for Travel, Speed_Wheel Suitcase for Travel, Graphite Blue', 'Textured Scratch resistant Polycarbonate shell\r\n\r\nThis lightweight trolley luggage comes with a Fixed combination Lock, 8 wheels with smooth maneuverability, and contrast beading that gives a premium look to the product\r\n\r\nThorium Neo is for every traveler who is looking for smart looking luggage with good utility point, Because of its new age trendy colors and contrast beading, the bag suits every need be it business or leisure travel. \r\n\r\nThe design on the bag gives it a very unique appearance.\r\n\r\nThe polycarbonate shell protects your luggage from scratches and mishandling.\r\n\r\nThe 5 year international Warranty ensures we have got you covered on all your trips.', '                                                        \r\n                                                        \r\n                                                        \r\n                                                        \r\n                       ', 3, 'Luggage', 0, 3999, 3999, 'product2.png', '2024-06-19 00:53:29', NULL),
(48, 0, 0, 'Van Gogh Printed Tote Bag', '30', 'Peach Blossom Van Gogh Printed Tote Bag for Women with Zip, Stylish Cotton Handbags, Canvas Tote Bags for College', 'Quality : Our Cotton Reusable Tote Bags are not only environmentally safe, but they are also built to last. With their exceptional strength-to-weight ratio and cross-stitched handles, these bags can comfortably carry a full load of groceries or a day\'s worth of supplies.\r\n\r\n\r\n\r\nOccasion : Our cotton bags are perfect for a variety of occasions. Whether you\'re going to the grocery shopping or need storage, these versatile bags are up for the task. With their spacious size and durability, they can hold more than single-use plastic bags and can be used repeatedly in your everyday life. By choosing these reusable cotton bags, you\'re making a sustainable choice that helps reduce plastic waste.\r\n\r\n\r\n\r\nPrint : We use Heat and Vinyl transfers for the prints.Recommending a gentle machine wash that can survive the wash cycle also do not iron on print.\r\n\r\n\r\n\r\nWash care : To keep our cotton bags in good condition,it\'s best not to wash them too often because the cotton fabric might shrink a little (about 5-10%). If you do need to wash them, use cold water and mild detergent. Make sure they\'re fully dry before ironing or adding vinyl transfers. Be careful with extreme conditions as they can affect the fabric\'s shape. By following these simple steps, you can keep our cotton shopping bags looking great and lasting a long time.', '                                                        \r\n                                                        \r\n                                                        \r\n                                                        \r\n                       ', 0.24, 'tote bag', 0, 1499, 1499, 'product3.png', '2024-06-19 00:53:43', NULL),
(49, 0, 1, 'Lyrovo Canvas Tote Bag', '30', 'Lyrovo Canvas Tote Bag for Women Purse Handbag', 'STURDY & DURABLE:6.5\" handle length, this printed canvas large tote bag for women is perfect as large capacity bag for women & ideal for daily use. The design shown appears on both sides.\r\n\r\n\r\n\r\nREASONS TO BUY LYROVO SHOPPING BAGS – These Shoppers tote can be reusable as Tote Bag | Shoppers bag | Handbag | Grocery Bag | Travel Bag |\r\n\r\nStorage Bag | Gift Bag for Diwali Gifting | Hand Bag | Party Bag | Multipurpose Jute bag is perfect bag for everyday shopping\r\n\r\n\r\n\r\nCARE INSTRUCTIONS: Dry Clean , It is recommended that a wet cloth is used to clean the bag', 'Crafted for versatility, designed for every journey.                            \r\n                                                        \r\n                                                        \r\n                            ', 0.4, 'Tote Bags', 0, 2499, 2499, 'product4.png', '2024-06-19 00:53:55', NULL),
(50, 0, 0, 'Uppercase Medium Backpack', '28', 'Backpack 3x more water resistant sustainable bag with Rainproof zippers for Men, Women, Boys and Girls', 'GRS CERTIFIED BACKPACK- Embrace sustainability without compromising on quality with our GRS-certified uppercase Daypack School/ College Bag. Made with over 50% recycled materials (License No. CMPY-158596), it features a padded compartment with breathable back padding with Air mesh, ensuring comfort and eco-conscious style for your journeys.\r\n\r\n\r\n\r\nWRINKLE-FREE & WATER RESISTANT BACKPACK- Experience unparalleled durability and style with our uppercase Daypack School/Office Bag. Handcrafted with premium, robust materials for a wrinkle-free, water-resistant design, featuring rainproof zippers for ultimate protection. Elevate your journey with this top-quality, long-lasting backpack!\r\n\r\n\r\n\r\nTROLLEY SLEEVE- Enhance your travel convenience with the uppercase. This backpack is equipped with a trolley sleeve, ensuring secure placement on your luggage. Effortlessly merge style and functionality while travelling.\r\n\r\n\r\n\r\nSTURDY STITCHING & VERSATILE STORAGE FOR YOUR ESSENTIALS- The uppercase Daypack school/college bag is meticulously designed with sturdy stitching, ensuring the right size for all essentials. Crafted for durability and functionality, it\'s an ideal companion for academic or professional pursuits, promising reliability and style in every stride.', '                            \r\n                                                        \r\n                            ', 0.38, 'Formal Backpack', 0, 4499, 4499, 'product5.png', '2024-06-19 00:54:10', NULL),
(51, 0, 0, 'Handcuffs Carry Garment Bag', '34', 'Handcuffs Carry On Bag Garment Bags for Travel Women Men Convertible Duffle Bag with Shoe Compartment Shoulder Strap, 2 in 1 Hanging Dress Suit Bag Weekend Bag (Black)', 'Feature: durable, lightweight, and water-resistant luggage suitcase strap along the back is convenient for fixing the foldable garment bag on the trolley of luggage, to secure the foldable garment bag slip over the handle of any rolling luggage for hands-free transport and make travelling simpler wrapped handles, convenient and comfortable for carrying.\r\n\r\nDetachable adjustable shoulder strap can adjust it to fit your shoulder well, provide a different way to carry-on, you can take it off whenever you need. As a good valentines day gifts for him her, thanksgiving gifts for men women metal hooks of strap is super sturdy;\r\n\r\nEasy to use strap attaches to joining d rings for max support. Luggage sleeve can be anti-theft and have lost-theft function high quality smooth zipper is made with sturdy titanium alloy material, ensure a secure & offering long time usage to carry on padded foam buckle tie holds your garments in place, ensuring that they don’t crease or crumple during travel well made of high density and water repellent polyester fabric, not easy get wet and ensure long lasting usage metal chain and hook support hang up in a closet or from a door at Handcuffs.\r\n\r\nHandcuffs provide the highest quality bags with the most reasonable cost so every customer can find a bag they actually love to carry. After assembly of large size beg for male female formal casual tour. To create products that inspire people to get out and live passionate lives; exploring, creating, and living life in the moment.', 'Elevate your style, but never compromise on security                            \r\n                                                        \r\n                                                        \r\n                            ', 1, 'garment Bags', 0, 6799, 6799, 'product6.png', '2024-06-19 00:54:23', NULL),
(52, 0, 1, 'Urban Jungle Venture Workpack', '28', 'Premuim Urban Jungle Venture Workpack 23 Liters Water Resistant, L-Open, Premium Polyester Laptop Backpack', 'Premium High-Strength Fabric: Crafted from premium, lightweight polyester fabric, this black backpack offers exceptional durability and water resistance, while the vibrant teal highlights make it extremely easy on the eyes. The easy-to-clean material ensures your backpack remains pristine, no matter where your journey takes you.\r\n\r\n\r\n\r\nEasy Access: This backpack features a unique fold-top opening for maximum storage and a secure strap closure for adjustable volume. A collapsible partition offers direct access to the main compartment from the laptop area offering easy retrieval of items.\r\n\r\n\r\n\r\nSuperior Laptop Protection and Organization: The 180-degree flat-open laptop and tablet sleeve, fits up to a 16\" laptop, allows for easy laptop and tablet access and robust protection. Designed with an internal organiser, easy access pockets and a hidden pocket for valuables, this backpack keeps items clutter-free and ensures that everything has its place.\r\n\r\n\r\n\r\nUncompromising Comfort and Convenience: Experience unparalleled comfort with superior back and sleeve padding, designed for extended wear. The intuitive trolley sleeve enhances mobility, ensuring your journey is as seamless as it is enjoyable.\r\n\r\n12 Month International Warranty: Maintenance is straightforward-simply wipe to clean. Coupled with a 12-month international warranty, this backpack stands as a testament to Urban Jungle\'s commitment to quality, offering peace of mind with every adventure. ', 'Adventure-ready!!                       \r\n                            ', 0.8, 'Formal Backpack', 10, 6999, 6299, 'product7.png', '2024-06-22 02:32:13', NULL),
(53, 0, 0, 'Premuim A/T Suitcase', '29', 'Premuim Trolley Bag for Travel FRONTEC Polycarbonate Hardsided Small Cabin Luggage Bag Suitcase for Travel', 'Durable Construction: Made from high-quality, lightweight polycarbonate material that resists impact and protects your belongings.\r\n\r\nExpandable Design: The suitcase features an expandable zipper, allowing for additional packing space when needed.\r\n\r\nSmooth Mobility: Equipped with four 360-degree spinner wheels, ensuring effortless maneuverability in all directions.\r\n\r\nSecure Locking System: Includes an integrated TSA-approved lock for added security and peace of mind during travel.\r\n\r\nErgonomic Handles: Telescopic handle with multiple height settings and comfortable top and side carry handles for easy lifting.\r\n\r\nSpacious Interior: Fully lined interior with multiple compartments, including a zippered divider, mesh pockets, and compression straps to keep your items organized and in place.\r\n\r\nStylish Design: Available in various colors and finishes, the Premium A/T Suitcase boasts a sleek and modern look suitable for any traveler.', '                            \r\n                                                        \r\n                                                        \r\n                            ', 1.35, 'Suitcases', 0, 14999, 14999, 'product8.png', '2024-06-19 00:54:40', NULL),
(56, 0, 0, 'Vanguard Camera Backpack', '35', 'Vanguard Camera Backpack Contains VEO Select 47 BF I 1-2 Pro DSLRs with lens upto 70-200mm,3-4 lenses, flash and accessories, Upto 15 inch(39cm), laptop, Tablet, WaterProof', 'Durable Build: Constructed from high-quality, weather-resistant materials to protect your gear from the elements.\r\n\r\nCustomizable Interior: Fully padded, adjustable dividers allow for personalized organization, accommodating various camera bodies, lenses, drones, and accessories.\r\n\r\nQuick Access: Side access panel provides instant reach to your camera, so you never miss a shot.\r\n\r\nComfortable Carry: Ergonomically designed shoulder straps, back padding, and adjustable waist belt distribute weight evenly for all-day comfort.\r\n\r\nDedicated Compartments: Separate compartments for a laptop up to 15 inches, a tablet, and personal items, keeping your tech and essentials organized and within reach.\r\n\r\nTripod Holder: External straps secure a tripod or monopod, ensuring you have all your gear with you.\r\n\r\nProtective Rain Cover: Included rain cover offers extra protection in inclement weather, ensuring your equipment stays dry and safe.\r\n\r\nTravel-Friendly: Meets carry-on size requirements for most airlines, making it a perfect companion for photographers on the go.', '                            \r\n                                                        \r\n                                                        \r\n                                                        \r\n                            ', 0.7, 'Formal Backpack', 0, 11999, 11999, 'product9.png', '2024-06-26 02:40:41', NULL),
(57, 0, 1, 'Cpixen Travel Backpack', '28', 'Cpixen Travel Backpack Large Capacity Men\'s Mother Bag Female Oxford Cloth College Student Bag ShouldeBag High Capacity Travel Bag', 'Durable Construction: Made from high-density, water-resistant polyester fabric, ensuring durability and protection from the elements.\r\n\r\nLarge Capacity: Spacious main compartment with multiple pockets and internal organizers for packing clothes, shoes, and travel essentials.\r\n\r\nSeparate Laptop Compartment: Padded compartment fits up to a 17-inch laptop and a tablet, keeping your devices secure and easily accessible.\r\n\r\nExternal USB Port: Built-in USB charger outside and built-in charging cable inside, offering convenient charging of your electronic devices on the go (power bank not included).\r\n\r\nComfortable Design: Ergonomic shoulder straps with adjustable chest strap and ventilated back padding for comfort and support during long journeys.\r\n\r\nAnti-Theft Features: Hidden zipper closures and a back pocket design for added security against pickpockets.\r\n\r\nWater Bottle Pockets: Dual side pockets for carrying water bottles or umbrellas, keeping hydration and rain gear easily accessible.\r\n\r\nVersatile Use: Suitable for various travel activities, including hiking, camping, business trips, and daily commuting.', 'Two Bags, One Purchase\r\nCustomize Your Carry                            \r\n                                                        \r\n                                                        \r\n                            ', 1.2, 'Formal Backpack', 0, 14999, 14999, 'bag3.png', '2024-12-01 06:04:47', NULL);
INSERT INTO `items` (`id`, `on_sale`, `home_items`, `name`, `category`, `description`, `about_this_product`, `caption`, `item_weight`, `generic_name`, `percentage`, `price`, `discounted_price`, `image`, `created_at`, `deleted_at`) VALUES
(58, 1, 0, 'New SBS Laptop Bag', '28', 'New SBS Waterproof Men Laptop Bags Computer Backpack with USB for Travel College School', 'Premium Materials: Crafted from high-quality, water-resistant nylon material, ensuring durability and protection against light rain and spills.\r\n\r\nPadded Laptop Compartment: Dedicated compartment with thick padding to safeguard laptops up to 15.6 inches, providing peace of mind while on the move.\r\n\r\nMultiple Compartments: Spacious main compartment with organizational pockets for documents, notebooks, and accessories such as chargers, pens, and keys.\r\n\r\nQuick Access Pocket: Front zippered pocket for easy access to frequently used items like smartphones, wallets, or passports.\r\n\r\nComfortable Carry: Adjustable shoulder strap with padding for comfortable wear over the shoulder or cross-body, plus sturdy handles for alternative carrying options.\r\n\r\nVersatile Design: Suitable for both men and women, with a minimalist yet stylish design that complements various outfits and settings.\r\n\r\nTravel-Friendly: Slim profile that fits under most airline seats, making it ideal for air travel or daily commuting.\r\n\r\nSecurity Features: Zippered closure and discreet pocket design to keep belongings secure while on the move.', 'Pack Your Dreams, Pursue Your Passion                            \r\n                            ', 1.3, 'Formal Backpack', 24, 6999, 5319, 'bag4.png', '2024-06-19 00:56:55', NULL),
(59, 1, 1, 'Loowoko Hiking Backpack', '35', 'Loowoko 50L Hiking Backpack, Waterproof Camping Essentials Bag with Rain Cover, 45+5 Liter Lightweight Backpacking Back Pack', 'Spacious Capacity: 50 liters of storage space with multiple compartments and pockets to organize gear efficiently.\r\n\r\nDurable Material: Made from high-quality, tear-resistant and water-repellent nylon fabric, designed to withstand the rigors of outdoor activities.\r\n\r\nComfortable Carrying System: Adjustable shoulder straps, chest strap, and padded waist belt distribute weight evenly, reducing strain on your shoulders and back.\r\n\r\nVentilation System: Breathable mesh back panel promotes airflow and keeps you cool during strenuous hikes.\r\n\r\nExternal Attachment Points: Various attachment loops and D-rings for hanging trekking poles, sleeping bags, or other gear externally.\r\n\r\nHydration System Compatible: Includes a hydration bladder compartment and tube access port (hydration bladder not included).\r\n\r\nRain Cover: Integrated rain cover stored in a bottom pocket for added protection during wet weather.\r\n\r\nVersatile Use: Suitable for hiking, camping, trekking, and other outdoor activities.\r\n', 'A Perfect Backpack for day hiking trips                            \r\n                                                        \r\n                            ', 1.8, 'Professional Backpacks', 50, 19999, 10000, 'bag2S.png', '2024-06-18 23:59:55', NULL),
(64, 0, 1, 'Miraggio Oversized Melissa Tote Bag', '28', 'Miraggio Oversized Melissa Tote Bag for Women with Adjustable & Detachable Sling Strap', 'TRENDY AND STYLISH, LATEST HANDBAGS FOR WOMEN: Set yourself a class apart and inspire the rest by carrying this Melissa Tote Bag from Miraggio. To stay ahead of the fashion pack, this tote is a must-have for your formal/office looks. Designed specially to serve the needs of working-class women. Inspired by and made for the quintessential Modern Woman!\r\nSPACIOUS HANDBAG FOR WOMEN: Melissa Oversized Tote Bag comes with 2 Main Compartment, 2 slip pockets and 1 zip pocket. This tote has space that fits your essentials easily like laptop (upto16\"), tablet, makeup pouch, phone & charger, tit-bits etc. Assured to hold your belongings safe with a zipper closure. It features 2 handles attached with metal loops to provide easy grip.\r\nYOUR TAKE EVRYWHERE TOTE: Roomy enough for all travel must-haves and more. The bag’s square shape affords plenty of room. It comes in two classic colors, ivory(with contrasting trims) & black.\r\nPREMIUM QUALITY HANDBAG FOR WOMEN: Crafted from signature - Faux leather comes with quality and durability. This classic tote comes with 2 handles and a detachable & Adjustable crossbody strap, making it a multi-purpose bag. Carry it as a top-handle bag, or even utilize the adjustable strap to use it as a shoulder bag or even crossbody.', '                            \r\n                                                        \r\n                                                        \r\n                            ', 0.5, 'Tote Bags', 8, 2999, 2759, 'product10.png', '2024-12-01 06:03:21', NULL),
(65, 0, 1, 'Storite Nylon Travel Duffle Bag', '31', 'Storite Nylon 47 Cm Imported Travel Duffle Bag, Sports Shoulder Bag for Women with Wet Pocket & Shoe Compartment Weekender Overnight Luggage Bag', 'he Travel Duffle Bag is elegant, fashionable and practical.\r\nThe Duffle Bag is perfect to help you carrying your traveling essentials, keeps your belongings organized.\r\nIt is designed with large capacity and wet pocket.\r\nMulti-zone design can provide exclusive space for luggage. The main compartment provides effective protection , and small luggage is placed in the exclusive compartment to keep the luggage neat and orderly.', '                            \r\n                            ', 0.8, 'Duffel Bags', 0, 1699, 1699, 'product11.png', '2024-06-26 03:13:19', NULL),
(73, 0, 1, 'LOOM TREE Art Portfolio Case Bag', '35', 'LOOM TREE Art Portfolio Case Portfolio Backpack Art Portfolio Carry Bag for Artwork | Art Supplies | Other Art Supplies', 'Water Resistancethe Art Portfolio Tote Bag Is Made Of Oxford Cloth Material, Rubber Handle, Adjustable Shoulder Strap, Lightweight And Waterproof To Protect Your Items Of Kind Artwork. Designthe Art Portfolio Case Includes A Top Handle And Adjustable Shoulder Straps For Comfortable Portability. Perfect For Traveling, Transporting Bag Organizer Supplies, And Other Stuff. Zipper Closurethe Portfolio Bag Comes With Convenient Zipper Closure, Art Portfolio Case Secures Your Precious Paints While Traveling. Portable Sizelength 54Cm/21.26Inch; Width 40Cm/15.75Inch; Thickness 1Cm/0.39Inch. Designed With Large Capacity, The Interior Of The Art Portfolio Case Is Built With A Full Width Interior Pocket To Carry Your Extra Supplies.', '                            \r\n                            ', 0.8, 'For Professionals', 0, 2499, 2499, 'poduct12.png', '2024-12-01 06:03:54', NULL),
(75, 0, 0, 'Herschel Supply Co. Little America Backpack', '28', 'Herschel Supply Co. Little America Backpack blends timeless mountaineering aesthetics with modern functionality', 'The Herschel Supply Co. Little America Backpack is renowned for its iconic blend of vintage mountaineering style and contemporary practicality. Its exterior is crafted with durable materials that exude rugged sophistication, making it suitable for both urban commutes and outdoor adventures. The backpack features a spacious main compartment secured by a drawstring closure and magnetic strap fastenings, offering easy access to its contents.\r\n\r\nInside, you\'ll find a plush, fleece-lined sleeve designed to safeguard laptops up to 15 inches in size, ensuring your tech essentials stay protected on the move. The backpack\'s front pocket provides additional organization for smaller items like keys, phones, and chargers, keeping them within quick reach. Comfort is prioritized with padded, ergonomic shoulder straps and a ventilated air mesh back panel that enhances airflow and reduces strain during extended wear.\r\n\r\nWhether you\'re navigating city streets or exploring remote trails, the Herschel Little America Backpack combines functional design with enduring style, making it a versatile companion for professionals, students, and adventurers alike.', '', 0.75, 'Formal Backpack', 0, 13999, 13999, 'product14.png', '2024-06-26 01:53:58', NULL),
(76, 0, 0, 'DroneGuard CS 400 from Lowepro', '35', 'DroneGuard CS 400 from Lowepro - Safely Carry and Organize All Your Quadcopter Drone Equipment in This Protective Case', 'The Drone Guard 400 case fits: DJI Phantom 1, 2 or 3, or 3DR Solo, or similar drone, quadcopter or flying camera form factor, RC/transmitter, blades, props, GoPro or other action video camera, batteries, cables, chargers, mounts, manuals, tools, etc.\r\nThe perfect, out-of-the-box solutions for carrying, organizing, storing and protecting your drone gear and all essentials\r\nForm Shell technology with lightweight, yet sturdy composite-shell construction offers superior protection for gear without adding weight or bulk\r\nA lightly padded back-pad includes attachable back-pad straps. Use for treks out to your flying location, or detach and pack away for less bulk or for long-distance travel\r\nIncludes dedicated storage for blades, props, GoPro or other action video camera, batteries, cables, chargers, mounts, manuals, etc.', '', 1.56, 'For Professional', 0, 7499, 7499, 'product13.png', '2024-06-26 02:00:09', NULL),
(77, 0, 1, 'CASALE Garment Bag', '34', 'Carry on Garment Bags Convertible Suit Bag with Shoes Compartment Waterproof 2 in 1 Travel Large Garment Bags Garment Duffle Bag for Men Black, Black', 'The carry on garment bag is made of high-quality polyester fiber, with shock-resistant and water-resistant/tear-resistant properties, which can better protect your suit or dress. The high-quality YKK zipper/buckle and hardware design can provide safety and durability for your business trip or vacation. The luggage strap on the back makes it easier for you to carry suitcases and clothing bags with you.When unfolded, it is a suit bag, and when assembled, it becomes a travel bag. This large garment bag is also designed with a shoe bag with a waterproof lining and two vents to store your shoes or clothes and separate wet and dirty shoes from the main compartment. A non-slip wear-resistant base is added to the bottom of the suit bag, which can provide safer and more stable protection when driving or going out in an airplane.The interior of the garment bags for travel has a large space and 2 inner buckles, which can keep your suit and clothes neat and wrinkle-free. And the 2 in 1 travel duffle bag has an extended inner lining, which can easily carry 2 suits and 1 dress, so that there are no more wrinkles on your dress or suit. The carry on garment bag comes with a hook design, you can hang the bag on the door or on the wall to save more space.', '', 1.2, 'Garment Bags', 0, 4999, 4999, 'product15.png', '2024-06-26 03:12:39', NULL),
(78, 0, 0, 'Assembly Cabin Suitcase', '29', 'Assembly Cabin Luggage Polycarbonate 20 Inches - Premium Hard-Sided Trolley Bag for Travel (Blue White, 40 L)-Stark', '100% Polycarbonate Material - Hard shell Cabin Luggage || Water & Scratch Resistant Suitcase\r\nKeyless TSA Lock Trolley Bag || 8 Spinner Wheels Luggage || Retractable Telescopic Trolley Handle\r\nAdditional Laptop Compartment (Upto 15.6 Inches Laptop) || Cabin Bag Capacity: 40 L || Dimension: 34cm, 24.5cm, 55cm (LxWxH)\r\nComplimentary Packing Organizer kit - 1 Toiletry Kit, 1 Packing Cube and 1 Shoe Bag\r\n5 Years of Warranty on Manufacturing Defects || To Register Your Warranty Kindly Scan the QR Code Attached to the Product.', '', 1.8, 'Suitcase', 0, 8499, 8499, 'product16.png', '2024-06-26 02:12:28', NULL),
(79, 0, 0, 'Delsey Paris Tiphanie Suitcase', '29', 'Delsey Paris Tiphanie 76 cms Large Check-in Polycarbonate Hard-sided 4 Double Wheel Luggage/Suitcase/Trolley Bag for Travel with TSA Lock (Steel Blue)', 'Delsey Paris\'s trolley bags for travel are a blend of Polycarbonate and ABS which make these travel bags for luggage extremely durableFour spinner wheels suitcase for travel with stable & multi-directional rolling\r\nIntegrated 3-dial TSA approved combination lock trolley bag/ luggage bag for travelCheckin trolley bag with spinner wheels: Enjoy the peace of mind with 2 year manufacturer warranty for our trolley bags for travel that includes the cost of repair for damage incurred from airlines or other common carriers. This applies when purchased as new and after registration', '                            \r\n                                                        \r\n                            ', 4.2, 'Suitcase', 0, 10499, 10499, 'product17.png', '2024-06-26 03:02:46', NULL),
(80, 0, 0, 'Storite Nylon Tarvel Duffle Bag', '28', 'Storite Nylon 51 cms Imported Travel Duffle Bag Muti- Pocket Sports Shoulder Bag for Women with Wet Pocket & Shoe Compartment Weekender Overnight Travel Luggage Bag (Green/White - 51x22x26 cm)', 'The Storite Nylon 51 cms Imported Travel Duffle Bag is designed for both functionality and style, making it an ideal choice for sports enthusiasts and travelers alike. Crafted from durable nylon, this duffle bag offers reliability and longevity, capable of withstanding the rigors of frequent use.\r\n\r\nIt features a spacious main compartment that provides ample room for your belongings, whether you\'re packing for a weekend getaway or carrying your gym essentials. The bag is equipped with multiple pockets, strategically placed to help you stay organized and store smaller items such as keys, wallets, and electronic gadgets conveniently.\r\n\r\nFor added convenience, the duffle bag includes sturdy handles and an adjustable shoulder strap, allowing you to carry it comfortably according to your preference. Its compact size, measuring 51 cms, ensures easy portability while complying with most airline carry-on restrictions.', '                            \r\n                            ', 0.45, 'Duffle Bag', 0, 3499, 3499, 'product18.png', '2024-06-26 02:25:35', NULL),
(81, 0, 0, 'PALAY Duffle Bags Travel Bags for Women', '31', 'PALAY® Duffle Bags Travel Bags for Women PU Waterproof Large Travel Duffel Bag Carry on Shoulder Bag with Shoulder Strap Carry On Bag for Trip', 'This travel luggage bag uses a high-quality PU leather construction, ensuring durability and longevity. The premium leather material not only enhances the bag\'s overall appearance and texture but also offers resistance against wear and tear. Whether you are traveling frequently or occasionally, this bag is built to withstand the rigors of your journeys, ensuring its longevity.Designed with trendy print patterns, this travel luggage bag adds a touch of style to your travels. Simple prints plus the elegant color design, these fashion prints allow you to express your personal style. Stand out from the crowd with this eye-catching bag, which is both practical and fashionable for any travel occasion. Also beautful and unique prints design also makes it convenient for you to find your bag during travels.Featuring one main large compartment and one small compartment, this travel luggage bag offers ample space for your essentials. It comfortably accommodates the clothing and toiletries of 1-2 people, making it ideal for short trips. The well-organized design ensures that your belongings remain tidy and easily accessible throughout your journey.', '', 0.8, '', 0, 7499, 7499, 'product19.png', '2024-06-26 02:25:19', NULL),
(82, 0, 0, 'Swiss Military Duffle Bag for Gym', '31', 'Swiss Military Duffle Bag for Gym, Duffle Bags for Travel, Men, Women| Spacious Gym Bag, Adj. Shoulder Strap & Comfortable Handle, Premium Polyester, Durable Zippers, Multi-Purpose, 27L, Grey', 'The Swiss Military Duffle Bag offers ample space for gym essentials, making it the perfect companion for your workouts. With an adjustable shoulder strap and comfortable handle, this duffle bag provides versatile and comfortable carrying options.Crafted from water-resistant fabric, this duffle bag keeps your belongings dry and protected from unexpected spills or light rain during outdoor activities.Made with sturdy materials and durable zippers, this multi-purpose duffle bag is built to withstand the rigors of travel and gym use.Ideal for gym sessions, travel, and everyday use, this duffle bag is designed to meet the needs of both men and women.', '', 0.5, 'Gym Duffel\'s', 0, 11499, 11499, 'product20.png', '2024-06-26 02:34:58', NULL),
(83, 0, 0, 'Fur Jaden Eco Conscious Vegan Garment Bag', '34', 'Fur Jaden Eco Conscious Vegan Leather Sustainable Garment Bag 40L Travel Weekender Cabin Bag with External Shoe Compartment (Tan)\r\nColour:Brown', 'Made from cruelty-free and eco-friendly materials, this duffle bag is a testament to our commitment to sustainable fashion. Built to endure the rigors of travel, the duffle bag features robust stitching and quality materials for long-lasting durability.Comfortably carry your duffle bag with ease using the padded grab handles, providing a soft grip for stress-free transportation. Adjustable Shoulder Strap: Customize your carrying experience with the adjustable and detachable shoulder strap, offering flexibility and comfort during extended journeys.Pack everything you need for your journey with the ample 40-liter capacity, providing room for clothing, essentials, and more. Ideal for weekend getaways, gym sessions, or short trips, this duffle bag combines functionality with a sleek and versatile design.', '', 1.2, 'Garment Bag', 0, 8999, 8999, 'product21.png', '2024-06-26 03:27:24', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `order_id` int NOT NULL,
  `item_id` int DEFAULT NULL,
  `customer_id` int DEFAULT NULL,
  `item` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `category_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `total_price` int NOT NULL,
  `gst_amount` int NOT NULL,
  `grand_total` int NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `phone` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `address` varchar(255) NOT NULL,
  `area` varchar(155) NOT NULL,
  `landmark` varchar(155) NOT NULL,
  `pincode` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `city` varchar(25) NOT NULL,
  `delivery_date` date DEFAULT NULL,
  `order_date` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `queries`
--

CREATE TABLE `queries` (
  `id` int NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `phone` varchar(10) DEFAULT NULL,
  `message` varchar(2555) DEFAULT NULL,
  `query_date` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `queries`
--

INSERT INTO `queries` (`id`, `name`, `email`, `phone`, `message`, `query_date`) VALUES
(12, 'jaymin', 'jaymin@gamil.com', '9874563210', 'Heyy, Can i order in bulk ??', '2024-06-17'),
(42, 'jd', 'jd@gmail.com', '8855779966', 'Heyy!! where can i see my orders?\r\n', '2024-06-19'),
(47, 'anyone', 'anyone@gmail.com', '68875877', 'heyy', '2024-06-24'),
(48, 'Jaymin', 'jaimindattani123@gmail.com', '9988775562', 'heuy there', '2024-12-01');

-- --------------------------------------------------------

--
-- Table structure for table `stores`
--

CREATE TABLE `stores` (
  `id` int NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `phone` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `stores`
--

INSERT INTO `stores` (`id`, `image`, `location`, `phone`, `created_at`, `deleted_at`) VALUES
(13, 'store2.png', 'Ambience Mall, New Delhi ', '+91-9988-7744-11', '2024-06-08 02:33:38', NULL),
(14, 'store1.png', 'Phoenix Palladium, Mumbai', '+91-9988-7777-77', '2024-06-08 02:33:38', NULL),
(15, 'store3.png', 'Alpha One Mall, Ahmedabad', '+91-9988-8888-77', '2024-06-08 02:33:38', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `tagline`
--

CREATE TABLE `tagline` (
  `id` int NOT NULL,
  `tagline` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `tagline`
--

INSERT INTO `tagline` (`id`, `tagline`, `created_at`, `deleted_at`) VALUES
(2, 'Bags that match your journey,\r\npricing that matches your budget!', '2024-06-08 02:57:05', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `team`
--

CREATE TABLE `team` (
  `id` int NOT NULL,
  `member` varchar(25) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `designation` varchar(25) DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `team`
--

INSERT INTO `team` (`id`, `member`, `image`, `designation`, `deleted_at`) VALUES
(21, 'Mittchel Fawset', 'person1.png', 'CMO', NULL),
(22, 'Benjamin meston', 'person2.png', 'CEO', NULL),
(23, 'Korina Villanueva', 'person3.png', 'Product Designer', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int NOT NULL,
  `name` varchar(30) DEFAULT NULL,
  `gender` varchar(15) NOT NULL,
  `email` varchar(30) DEFAULT NULL,
  `password` varchar(30) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `name`, `gender`, `email`, `password`, `created_at`, `deleted_at`) VALUES
(3, 'tester', 'male', 'tester@gmail.com', '1234', '2024-06-18 01:55:56', '2024-06-18 01:55:56'),
(6, 'test2', 'male', 'test2@gmail.com', '123456', '2024-12-13 10:18:54', '2024-12-13 10:18:54');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `password` (`password`);

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`category_id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`order_id`);

--
-- Indexes for table `queries`
--
ALTER TABLE `queries`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `order_id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=67;

--
-- AUTO_INCREMENT for table `queries`
--
ALTER TABLE `queries`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
